import { FaUsers, FaUser, FaCalendarDay, FaUserAlt } from 'react-icons/fa';
import { BsCalendar2DateFill, BsCalendarDate } from 'react-icons/bs';
import { IoMdTime } from 'react-icons/io';
import { BiTimeFive } from 'react-icons/bi';

const newChangeInputs = [
	{
		key: 0,
		name: 'coverName',
		optionsList: [],
		icon: <FaUser />,
		errorMessage: '',
		value: '',
		placeHolder: 'Quien cubre',
	},
	{
		key: 1,
		name: 'coverDate',
		optionsList: [],
		icon: <BsCalendarDate />,
		errorMessage: '',
		value: '',
		placeHolder: 'Fecha a cubrir',
		calendar: true,
	},
	{
		key: 2,
		name: 'coverTime',
		optionsList: ['6 a 14 hs.', '14 a 22 hs.', '22 a 6 hs.'],
		errorMessage: '',
		icon: <IoMdTime />,
		value: '',
		placeHolder: 'Horario a cubrir',
	},
	{
		key: 3,
		name: 'coverDay',
		optionsList: [],
		icon: <FaCalendarDay />,
		errorMessage: '',
		value: '',
		placeHolder: 'Día a cubrir',
		disabled: true,
	},
	{
		key: 4,
		name: 'coverGuardId',
		optionsList: [],
		icon: <FaUsers />,
		errorMessage: '',
		value: '',
		placeHolder: 'Guardia a cubrir',
		disabled: true,
	},
	{
		key: 5,
		name: 'returnName',
		optionsList: [],
		icon: <FaUserAlt />,
		errorMessage: '',
		value: '',
		placeHolder: 'Quien devuelve',
	},
	{
		key: 6,
		name: 'returnDate',
		optionsList: [],
		icon: <BsCalendar2DateFill />,
		errorMessage: '',
		value: '',
		placeHolder: 'Fecha a devolver',
		calendar: true,
	},
	{
		key: 7,
		name: 'returnTime',
		optionsList: ['6 a 14 hs.', '14 a 22 hs.', '22 a 6 hs.'],
		errorMessage: '',
		icon: <BiTimeFive />,
		value: '',
		placeHolder: 'Horario a devolver',
	},
	{
		key: 8,
		name: 'returnDay',
		optionsList: [],
		icon: <FaCalendarDay />,
		errorMessage: '',
		value: '',
		placeHolder: 'Día a devolver',
		disabled: true,
	},
	{
		key: 9,
		name: 'returnGuardId',
		optionsList: [],
		icon: <FaUsers />,
		errorMessage: '',
		value: '',
		placeHolder: 'Guardia a devolver',
		disabled: true,
	},
];

export default newChangeInputs;
