import { FaUsers, FaUser, FaIdCard, FaBuilding, FaEnvelope, FaKey } from 'react-icons/fa';

const registerInputs = [
	{
		key: 0,
		name: 'userName',
		password: false,
		section: false,
		icon: <FaUser />,
		errorMessage: '',
		value: '',
		placeHolder: 'Nombre de usuario',
	},
	{
		key: 1,
		name: 'lastName',
		password: false,
		section: false,
		icon: <FaUser />,
		errorMessage: '',
		value: '',
		placeHolder: 'Apellido',
	},
	{
		key: 2,
		name: 'firstName',
		section: false,
		password: false,
		errorMessage: '',
		icon: <FaUser />,
		value: '',
		placeHolder: 'Nombre',
	},
	{
		key: 3,
		name: 'ni',
		section: false,
		password: false,
		icon: <FaIdCard />,
		errorMessage: '',
		value: '',
		placeHolder: 'NI',
	},
	{
		key: 4,
		name: 'section',
		section: true,
		password: false,
		icon: <FaBuilding />,
		errorMessage: '',
		value: '',
		placeHolder: 'Sección',
	},
	{
		key: 5,
		name: 'guard',
		section: false,
		password: false,
		icon: <FaUsers />,
		errorMessage: '',
		value: '',
		placeHolder: 'Guardia',
	},
	{
		key: 6,
		name: 'email',
		section: false,
		password: false,
		icon: <FaEnvelope />,
		errorMessage: '',
		value: '',
		placeHolder: 'Correo electrónico',
	},
	{
		key: 7,
		name: 'password',
		section: false,
		password: true,
		icon: <FaKey />,
		errorMessage: '',
		value: '',
		placeHolder: 'Contraseña',
	},
	{
		key: 8,
		name: 'repeatPassword',
		section: false,
		password: true,
		icon: <FaKey />,
		errorMessage: '',
		value: '',
		placeHolder: 'Repetir password',
	},
];

export default registerInputs;
